imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ExellBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.user_carteidentite: /cni

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
      - bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


vich_uploader:
    db_driver: orm
    mappings:
        user_carteidentite:
            uri_prefix: '%app.path.user_carteidentite%'
            upload_destination: '%kernel.root_dir%/../web/cni'

easy_admin:
    site_name: 'ByNeuf'
    entities:
        - ExellBundle\Entity\Images
        - ExellBundle\Entity\Agence
        - ExellBundle\Entity\TypeInvest
        - ExellBundle\Entity\Departement
        - ExellBundle\Entity\Categorie
        - ExellBundle\Entity\Adresse
        - ExellBundle\Entity\Prix
        - ExellBundle\Entity\Presentation
        - ExellBundle\Entity\Offres
        - ExellBundle\Entity\Bien
        - ExellBundle\Entity\Utilisateur
    design:
        form_theme: 'vertical'
        brand_color: '#264ACA'
        color_scheme: 'light'
        menu:
            - {label: 'Images des biens'}
            - {entity: 'Images' }
            - {label: 'Agence qui est rattacher au bien'}
            - {entity: 'Agence' }
            - {label: 'Type pour investissement '}
            - {entity: 'TypeInvest' }
            - {label: 'Département et Adresse du bien'}
            - {entity: 'Departement' }
            - {entity: 'Adresse' }
            - {label: 'Categorie du bien (Villa, Appartement) '}
            - {entity: 'Categorie' }
            - {label: 'Prix du Bien '}
            - {entity: 'Prix' }
            - {label: 'Présentation du bien'}
            - {entity: 'Presentation'}
            - {label: 'Offres spécifique ( frais de notaire par exemple ) '}
            - {entity: 'Offres' }
            - {entity: 'Bien' }
            - {label: 'Partie utilisateur'}
            - {entity: 'Utilisateur' }



fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: ExellBundle\Entity\Utilisateur
    service:
        mailer: fos_user.mailer.default
    registration:
        confirmation:
            enabled: true
        form:
          type: ExellBundle\Form\RegistrationType
    from_email:
        address: contact@exellfinance.com
        sender_name: Exell Fincance

circle_rest_client:
    curl:
      defaults:
        CURLOPT_HTTPHEADER:     [ 'Content-Type: application/json' ]
        CURLOPT_FOLLOWLOCATION: true
