<?php

namespace ExellBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends EntityRepository
{
    public function findByDepartementAndTypeInvest($dep,$typeInvest)
    {
        $query = $this->createQueryBuilder('a');
        $query->where('a.departement = :departement')
            ->andWhere('a.typeinvest = :typeInvest')
            ->setParameters(array(
                'departement' => $dep,
                'typeInvest' => $typeInvest,
        ));

        return $query->getQuery()->getResult();
    }
}
