<?php

namespace ExellBundle\Repository;

/**
 * TypeInvestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeInvestRepository extends \Doctrine\ORM\EntityRepository
{
}
