services:
#    exell.example:
#        class: ExellBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    ExellBundle\Form\Type\SearchType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]